version: '3.8'
volumes:
  vol_database_python:
  vol_database_java:

networks:
  project_network:
    driver: bridge

services:
  database_python:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=siakoo
    volumes:
        - vol_database_python:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
        - project_network

  database_java:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=siakoo
    volumes:
        - vol_database_java:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
        - project_network

  flask:
    build: ./build/flask
    restart: on-failure
    ports:
      - "8082:5000"
    volumes:
      - ./python:/usr/src/app
    environment:
      - DB_HOSTNAME=database_python
      - DB_NAME=blog
      - DB_USERNAME=root
      - DB_PASSWORD=siakoo
    networks:
      - project_network

  spring:
    build: ./build/spring
    ports:
      - "8083:8080"
    restart: on-failure
    environment:
      - DB_HOSTNAME=database_java
      - DB_NAME=blog
      - DB_USERNAME=root
      - DB_PASSWORD=siakoo
    networks:
      - project_network